[2025-01-13T01:29:51.770+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-13T01:29:51.787+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weekly_ufc_dag.run_etl_script scheduled__2025-01-05T00:00:00+00:00 [queued]>
[2025-01-13T01:29:51.795+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weekly_ufc_dag.run_etl_script scheduled__2025-01-05T00:00:00+00:00 [queued]>
[2025-01-13T01:29:51.795+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-13T01:29:51.811+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): run_etl_script> on 2025-01-05 00:00:00+00:00
[2025-01-13T01:29:51.819+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=79) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-13T01:29:51.821+0000] {standard_task_runner.py:72} INFO - Started process 89 to run task
[2025-01-13T01:29:51.821+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weekly_ufc_dag', 'run_etl_script', 'scheduled__2025-01-05T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp0yue3115']
[2025-01-13T01:29:51.822+0000] {standard_task_runner.py:105} INFO - Job 7: Subtask run_etl_script
[2025-01-13T01:29:51.874+0000] {task_command.py:467} INFO - Running <TaskInstance: weekly_ufc_dag.run_etl_script scheduled__2025-01-05T00:00:00+00:00 [running]> on host bcb22ad01083
[2025-01-13T01:29:51.958+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weekly_ufc_dag' AIRFLOW_CTX_TASK_ID='run_etl_script' AIRFLOW_CTX_EXECUTION_DATE='2025-01-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-05T00:00:00+00:00'
[2025-01-13T01:29:51.959+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-13T01:29:51.960+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-13T01:29:51.960+0000] {logging_mixin.py:190} INFO - Current task name:run_etl_script state:running start_date:2025-01-13 01:29:51.788335+00:00
[2025-01-13T01:29:51.961+0000] {logging_mixin.py:190} INFO - Dag name:weekly_ufc_dag and current dag run status:running
[2025-01-13T01:29:51.961+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-13T01:29:51.962+0000] {main.py:8} INFO - ETL process started...
[2025-01-13T01:29:52.287+0000] {logging_mixin.py:190} INFO - Connection successful!
[2025-01-13T01:29:53.820+0000] {logging_mixin.py:190} INFO - No fights available and No events available
[2025-01-13T01:29:53.839+0000] {logging_mixin.py:190} INFO - No fights available
[2025-01-13T01:29:54.049+0000] {logging_mixin.py:190} INFO - Connection successful!
[2025-01-13T01:29:54.050+0000] {logging_mixin.py:190} INFO - Could not get the fighter data
[2025-01-13T01:29:54.052+0000] {main.py:34} INFO - No data to be added to the database.
[2025-01-13T01:29:54.053+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-13T01:29:54.060+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-13T01:29:54.061+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=weekly_ufc_dag, task_id=run_etl_script, run_id=scheduled__2025-01-05T00:00:00+00:00, execution_date=20250105T000000, start_date=20250113T012951, end_date=20250113T012954
[2025-01-13T01:29:54.074+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-13T01:29:54.075+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-13T01:29:54.076+0000] {logging_mixin.py:190} INFO - Dag name:weekly_ufc_dag queued_at:2025-01-13 01:29:46.950935+00:00
[2025-01-13T01:29:54.076+0000] {logging_mixin.py:190} INFO - Task hostname:bcb22ad01083 operator:PythonOperator
[2025-01-13T01:29:54.124+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-13T01:29:54.136+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-13T01:29:54.140+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
