[2025-01-13T01:31:14.088+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-13T01:31:14.100+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weekly_ufc_dag.run_etl_script manual__2025-01-13T01:31:11.822174+00:00 [queued]>
[2025-01-13T01:31:14.106+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weekly_ufc_dag.run_etl_script manual__2025-01-13T01:31:11.822174+00:00 [queued]>
[2025-01-13T01:31:14.107+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-13T01:31:14.118+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): run_etl_script> on 2025-01-13 01:31:11.822174+00:00
[2025-01-13T01:31:14.125+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=106) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-13T01:31:14.127+0000] {standard_task_runner.py:72} INFO - Started process 108 to run task
[2025-01-13T01:31:14.127+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weekly_ufc_dag', 'run_etl_script', 'manual__2025-01-13T01:31:11.822174+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp3_waxmkq']
[2025-01-13T01:31:14.128+0000] {standard_task_runner.py:105} INFO - Job 8: Subtask run_etl_script
[2025-01-13T01:31:14.165+0000] {task_command.py:467} INFO - Running <TaskInstance: weekly_ufc_dag.run_etl_script manual__2025-01-13T01:31:11.822174+00:00 [running]> on host bcb22ad01083
[2025-01-13T01:31:14.230+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weekly_ufc_dag' AIRFLOW_CTX_TASK_ID='run_etl_script' AIRFLOW_CTX_EXECUTION_DATE='2025-01-13T01:31:11.822174+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-13T01:31:11.822174+00:00'
[2025-01-13T01:31:14.232+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-13T01:31:14.233+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-13T01:31:14.234+0000] {logging_mixin.py:190} INFO - Current task name:run_etl_script state:running start_date:2025-01-13 01:31:14.101073+00:00
[2025-01-13T01:31:14.234+0000] {logging_mixin.py:190} INFO - Dag name:weekly_ufc_dag and current dag run status:running
[2025-01-13T01:31:14.235+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-13T01:31:14.236+0000] {main.py:8} INFO - ETL process started...
[2025-01-13T01:31:14.538+0000] {logging_mixin.py:190} INFO - Connection successful!
[2025-01-13T01:31:15.642+0000] {logging_mixin.py:190} INFO - No fights available and No events available
[2025-01-13T01:31:15.662+0000] {logging_mixin.py:190} INFO - No fights available
[2025-01-13T01:31:15.832+0000] {logging_mixin.py:190} INFO - Connection successful!
[2025-01-13T01:31:15.832+0000] {logging_mixin.py:190} INFO - Could not get the fighter data
[2025-01-13T01:31:15.834+0000] {main.py:34} INFO - No data to be added to the database.
[2025-01-13T01:31:15.835+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-13T01:31:15.842+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-13T01:31:15.843+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=weekly_ufc_dag, task_id=run_etl_script, run_id=manual__2025-01-13T01:31:11.822174+00:00, execution_date=20250113T013111, start_date=20250113T013114, end_date=20250113T013115
[2025-01-13T01:31:15.854+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-13T01:31:15.855+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-13T01:31:15.856+0000] {logging_mixin.py:190} INFO - Dag name:weekly_ufc_dag queued_at:2025-01-13 01:31:11.835056+00:00
[2025-01-13T01:31:15.856+0000] {logging_mixin.py:190} INFO - Task hostname:bcb22ad01083 operator:PythonOperator
[2025-01-13T01:31:15.868+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-13T01:31:15.881+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-13T01:31:15.886+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
